dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - Robert29000/TestSwap-core@1.0.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
      - '@testswapcore=Robert29000/TestSwap-core@1.0.0'